# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/max/Documents/ZebraHead22/Polina/scripts/infogypsies.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.browse_btn = QtWidgets.QPushButton(self.centralwidget)
        self.browse_btn.setGeometry(QtCore.QRect(20, 30, 131, 51))
        self.browse_btn.setObjectName("browse_btn")
        self.process_btn = QtWidgets.QPushButton(self.centralwidget)
        self.process_btn.setGeometry(QtCore.QRect(30, 110, 141, 91))
        self.process_btn.setObjectName("process_btn")
        self.export_btn = QtWidgets.QPushButton(self.centralwidget)
        self.export_btn.setGeometry(QtCore.QRect(70, 250, 113, 32))
        self.export_btn.setObjectName("export_btn")
        self.csvfile_label = QtWidgets.QLabel(self.centralwidget)
        self.csvfile_label.setGeometry(QtCore.QRect(200, 40, 501, 16))
        self.csvfile_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.csvfile_label.setObjectName("csvfile_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.browse_btn.setText(_translate("MainWindow", "Browse..."))
        self.process_btn.setText(_translate("MainWindow", "Обработать"))
        self.export_btn.setText(_translate("MainWindow", "Export"))
        self.csvfile_label.setText(_translate("MainWindow", "Выберите .CSV файл"))
